### ISSUE TITLE
Caching of the artifect

### ISSUE THREAD

**Issue by hegelstad** [jamiebuilds/dependency-free#1]
Wouldn’t it be much easier to cache the build artifact created by npm install? The artifact can be reused for each parallell job and it must only be rebuilt once the hash of package.json changes. I think CircleCI employ this method.

**Comment by jamiebuilds** [comment]
I would still cache everything I can with this method.

In fact this method makes individual `node_modules` even more cacheable because changing a dependency for your lint task doesn't invalidate the cached `node_modules` for your unit test task.

This strategy isn't for everyone, if caching `node_modules` is enough to keep your builds fast, it's all you should be doing.
